########################################################################################################################
# Builder image
########################################################################################################################
FROM ubuntu:20.04 as builder-image

# avoid stuck build due to user prompt
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y python3.9 python3.9-venv build-essential wget && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# create and activate virtual environment
# using final folder name to avoid path issues with packages
ENV VIRTUAL_ENV=/venv
RUN python3.9 -m venv ${VIRTUAL_ENV}
ENV PATH=${PATH}:${VIRTUAL_ENV}/bin

# install requirements
COPY requirements.txt .
RUN pip install --no-cache-dir wheel
RUN pip install --no-cache-dir -r ./requirements.txt

# Download and extract GCC compilers.
# Releases: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

RUN mkdir -p /gcc

RUN mkdir -p /gcc/7
RUN wget --no-check-certificate https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2 \
    && tar -xvf gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2 --strip-components=1 -C /gcc/7 \
    && rm gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2

RUN mkdir -p /gcc/9
RUN wget --no-check-certificate https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 \
    && tar -xvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 --strip-components=1 -C /gcc/9 \
    && rm gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2


########################################################################################################################
# Runner image image
########################################################################################################################
FROM ubuntu:20.04 as runner-image

# avoid stuck build due to user prompt
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y python3.9-venv make git astyle locales && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# Set locales. Needed by Astyle.
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

# Copy the extracted compiler files.
COPY --from=builder-image /gcc /gcc

# Set the compiler variables
ENV GCC_COMPILER_7_2_1 /gcc/7/bin
ENV GCC_COMPILER_9_2_1 /gcc/9/bin

# Set up the compiler path to the latest version
ENV PATH=${PATH}:${GCC_COMPILER_9_2_1}

# Set up the Astyle path
ENV PATH=${PATH}:/astyle/build/gcc/bin

# Copy virtual environment from builder image
COPY --from=builder-image /venv /venv

# Make sure that the standard python installation points to the explicitely installed one
RUN ln -sf python3.9 /usr/bin/python3

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Create project folder
RUN mkdir /project
WORKDIR /project

# Switching to a non-root user, please refer to https://aka.ms/vscode-docker-python-user-rights
RUN useradd appuser && chown -R appuser /project
USER appuser

# activate virtual environment
ENV VIRTUAL_ENV=/venv
ENV PATH=${PATH}:${VIRTUAL_ENV}/bin

# Since some makefiles call 'python3' we need to make the venv packages available by setting the library path
ENV PYTHONPATH=${VIRTUAL_ENV}/lib/python3.9/site-packages/

# Set the bash shell
ENV SHELL=/bin/bash
